export const actionTypes = {
  SET_GAME_TIME: '[TimeLine] SET_GAME_TIME',
  CHANGE_GAME_CONFIG_STATE: '[TimeLine] CHANGE_GAME_CONFIG_STATE',
  FETCH_RESERVED_GAMES: '[TimeLine] FETCH_RESERVED_GAMES',
  FETCH_RESERVED_GAMES_SUCCESS: '[TimeLine] FETCH_RESERVED_GAMES_SUCCESS',
  FETCH_RESERVED_GAMES_FAIL: '[TimeLine] FETCH_RESERVED_GAMES_FAIL',
};

