export const actionTypes = {
  ADD_NEW_GAME: '[TimeLine] ADD_NEW_GAME',
  ADD_NEW_GAME_SUCCESS: '[TimeLine] ADD_NEW_GAME_SUCCESS',
  ADD_NEW_GAME_FAIL: '[TimeLine] ADD_NEW_GAME_FAIL',
  CHANGE_GAME_CONFIG_STATE: '[TimeLine] CHANGE_GAME_CONFIG_STATE',
  FETCH_RESERVED_GAMES: '[TimeLine] FETCH_RESERVED_GAMES',
  FETCH_RESERVED_GAMES_SUCCESS: '[TimeLine] FETCH_RESERVED_GAMES_SUCCESS',
  FETCH_RESERVED_GAMES_FAIL: '[TimeLine] FETCH_RESERVED_GAMES_FAIL',
  ZOOM_TIMELINE: '[TimeLine] ZOOM_TIMELINE',
  SET_GAME_TYPE: '[GameReservation] SET_GAME_TYPE',
  SET_GAME_TIME: '[GameReservation] SET_GAME_TIME',
};
