export const actionTypes = {
    SET_DIRECT_CHAT_MODE: '[CHAT] SET_DIRECT_CHAT_MODE',
    SET_GLOBAL_CHAT_MODE: '[CHAT] SET_GLOBAL_CHAT_MODE',
    ADD_GLOBAL_CHAT_MESSAGE: '[CHAT] ADD_GLOBAL_CHAT_MESSAGE',
    ADD_DIRECT_CHAT_MESSAGE: '[CHAT] ADD_DIRECT_CHAT_MESSAGE',

    FETCH_DIRECT_CHAT_MESSAGES: '[CHAT] FETCH_DIRECT_CHAT_MESSAGES',
    FETCH_DIRECT_CHAT_MESSAGES_SUCCESS: '[CHAT] FETCH_DIRECT_CHAT_MESSAGES_SUCCESS',
    FETCH_DIRECT_CHAT_MESSAGES_FAIL: '[CHAT] FETCH_DIRECT_CHAT_MESSAGES_FAIL',
};
  