export const actionTypes = {
  SOCIAL_AUTH_GOOGLE: '[Auth] SOCIAL_AUTH_GOOGLE',
  SOCIAL_AUTH_GITHUB: '[Auth] SOCIAL_AUTH_GITHUB',
  SOCIAL_AUTH_SUCCESS: '[Auth] SOCIAL_AUTH_SUCCESS',
  SOCIAL_AUTH_FAIL: '[Auth] SOCIAL_AUTH_FAIL',
};
