export const actionTypes = {
    SET_DIRECT_CHAT_MODE: '[CHAT] SET_DIRECT_CHAT_MODE',
    SET_GLOBAL_CHAT_MODE: '[CHAT] SET_GLOBAL_CHAT_MODE',
    ADD_GLOBAL_CHAT_MESSAGE: '[CHAT] ADD_GLOBAL_CHAT_MESSAGE',
};
  